BookingAppv7/Controllers/Reservations2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingAppv7.Models;

namespace BookingAppv7.Controllers
{
    public class Reservations2Controller : Controller
    {
        private readonly TestDbContext _context;

        public Reservations2Controller(TestDbContext context)
        {
            _context = context;
        }

        // GET: Reservations2
        public async Task<IActionResult> Index()
        {
            var testDbContext = _context.Reservations.Include(r => r.Showing);
            return View(await testDbContext.ToListAsync());
        }

        // GET: Reservations2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Showing)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations2/Create
        public IActionResult Create()
        {
            ViewData["Showingid"] = new SelectList(_context.Showings, "Id", "Id");
            return View();
        }

        // POST: Reservations2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Showingid,Seatsno")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Showingid"] = new SelectList(_context.Showings, "Id", "Id", reservation.Showingid);
            return View(reservation);
        }

        // GET: Reservations2/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["Showingid"] = new SelectList(_context.Showings, "Id", "Id", reservation.Showingid);
            return View(reservation);
        }

        // POST: Reservations2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Showingid,Seatsno")] Reservation reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Showingid"] = new SelectList(_context.Showings, "Id", "Id", reservation.Showingid);
            return View(reservation);
        }

        // GET: Reservations2/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Showing)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservations.Remove(reservation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.Id == id);
        }
    }
}

BookingAppv7/Controllers/Showings2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingAppv7.Models;

namespace BookingAppv7.Controllers
{
    public class Showings2Controller : Controller
    {
        private readonly TestDbContext _context;

        public Showings2Controller(TestDbContext context)
        {
            _context = context;
        }

        // GET: Showings2
        public async Task<IActionResult> Index()
        {
            var testDbContext = _context.Showings.Include(s => s.Movie);
            return View(await testDbContext.ToListAsync());
        }

        // GET: Showings2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showing = await _context.Showings
                .Include(s => s.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (showing == null)
            {
                return NotFound();
            }

            return View(showing);
        }

        // GET: Showings2/Create
        public IActionResult Create()
        {
            ViewData["Movieid"] = new SelectList(_context.Movies, "Id", "Id");
            return View();
        }

        // POST: Showings2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Movieid,Datet,Seats")] Showing showing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(showing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Movieid"] = new SelectList(_context.Movies, "Id", "Id", showing.Movieid);
            return View(showing);
        }

        // GET: Showings2/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showing = await _context.Showings.FindAsync(id);
            if (showing == null)
            {
                return NotFound();
            }
            ViewData["Movieid"] = new SelectList(_context.Movies, "Id", "Id", showing.Movieid);
            return View(showing);
        }

        // POST: Showings2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Movieid,Datet,Seats")] Showing showing)
        {
            if (id != showing.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(showing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowingExists(showing.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Movieid"] = new SelectList(_context.Movies, "Id", "Id", showing.Movieid);
            return View(showing);
        }

        // GET: Showings2/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showing = await _context.Showings
                .Include(s => s.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (showing == null)
            {
                return NotFound();
            }

            return View(showing);
        }

        // POST: Showings2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var showing = await _context.Showings.FindAsync(id);
            if (showing != null)
            {
                _context.Showings.Remove(showing);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowingExists(int id)
        {
            return _context.Showings.Any(e => e.Id == id);
        }
    }
}

BookingAppv7/Views/Showings2/Create.cshtml
@model BookingAppv7.Models.Showing

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Showing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movieid" class="control-label"></label>
                <select asp-for="Movieid" class ="form-control" asp-items="ViewBag.Movieid"></select>
            </div>
            <div class="form-group">
                <label asp-for="Datet" class="control-label"></label>
                <input asp-for="Datet" class="form-control" />
                <span asp-validation-for="Datet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seats" class="control-label"></label>
                <input asp-for="Seats" class="form-control" />
                <span asp-validation-for="Seats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookingAppv7/Views/Showings2/Delete.cshtml
@model BookingAppv7.Models.Showing

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Showing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookingAppv7/Views/Showings2/Details.cshtml
@model BookingAppv7.Models.Showing

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Showing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookingAppv7/Views/Showings2/Edit.cshtml
@model BookingAppv7.Models.Showing

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Showing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Movieid" class="control-label"></label>
                <select asp-for="Movieid" class="form-control" asp-items="ViewBag.Movieid"></select>
                <span asp-validation-for="Movieid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datet" class="control-label"></label>
                <input asp-for="Datet" class="form-control" />
                <span asp-validation-for="Datet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seats" class="control-label"></label>
                <input asp-for="Seats" class="form-control" />
                <span asp-validation-for="Seats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookingAppv7/Views/Showings2/Index.cshtml
@model IEnumerable<BookingAppv7.Models.Showing>

@{
    ViewData["Title"] = "Date of Showings";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Datet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Datet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Id)
            </td>
            <td>
            <input type="submit" onclick="location.href='@Url.Action("Index","Reservations2")'" value="Buy Ticket" />
            </td>
        </tr>
}
    </tbody>
</table>